# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: prime_level.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='prime_level.proto',
  package='freefire',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x11prime_level.proto\x12\x08\x66reefire\"*\n\x05Users\x12!\n\tbasicinfo\x18\x01 \x03(\x0b\x32\x0e.freefire.info\"\x1c\n\x05prime\x12\x13\n\x0bprime_level\x18\x02 \x01(\r\">\n\x04info\x12\x10\n\x08username\x18\x03 \x01(\t\x12$\n\x0bprime_level\x18L \x01(\x0b\x32\x0f.freefire.primeb\x06proto3'
)




_USERS = _descriptor.Descriptor(
  name='Users',
  full_name='freefire.Users',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='basicinfo', full_name='freefire.Users.basicinfo', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=31,
  serialized_end=73,
)


_PRIME = _descriptor.Descriptor(
  name='prime',
  full_name='freefire.prime',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='prime_level', full_name='freefire.prime.prime_level', index=0,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=75,
  serialized_end=103,
)


_INFO = _descriptor.Descriptor(
  name='info',
  full_name='freefire.info',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='username', full_name='freefire.info.username', index=0,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='prime_level', full_name='freefire.info.prime_level', index=1,
      number=76, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=105,
  serialized_end=167,
)

_USERS.fields_by_name['basicinfo'].message_type = _INFO
_INFO.fields_by_name['prime_level'].message_type = _PRIME
DESCRIPTOR.message_types_by_name['Users'] = _USERS
DESCRIPTOR.message_types_by_name['prime'] = _PRIME
DESCRIPTOR.message_types_by_name['info'] = _INFO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Users = _reflection.GeneratedProtocolMessageType('Users', (_message.Message,), {
  'DESCRIPTOR' : _USERS,
  '__module__' : 'prime_level_pb2'
  # @@protoc_insertion_point(class_scope:freefire.Users)
  })
_sym_db.RegisterMessage(Users)

prime = _reflection.GeneratedProtocolMessageType('prime', (_message.Message,), {
  'DESCRIPTOR' : _PRIME,
  '__module__' : 'prime_level_pb2'
  # @@protoc_insertion_point(class_scope:freefire.prime)
  })
_sym_db.RegisterMessage(prime)

info = _reflection.GeneratedProtocolMessageType('info', (_message.Message,), {
  'DESCRIPTOR' : _INFO,
  '__module__' : 'prime_level_pb2'
  # @@protoc_insertion_point(class_scope:freefire.info)
  })
_sym_db.RegisterMessage(info)


# @@protoc_insertion_point(module_scope)
